# Generated by Django 2.1.7 on 2019-04-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug2LineName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bug2NotiPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bug2Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BugInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('isNotify', models.BooleanField(default=False)),
                ('createPeople', models.CharField(max_length=50)),
                ('lastModifyPeople', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BugLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=50, unique=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BugReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, unique=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BugSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, unique=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineName', models.CharField(max_length=50, unique=True)),
                ('owner', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotiPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('owner', models.CharField(max_length=50)),
                ('reviewer', models.CharField(max_length=50)),
                ('finishStatus', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformName', models.CharField(max_length=50, unique=True)),
                ('owner', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('privilege', models.SmallIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='creatUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prob_createUser', to='box.User'),
        ),
        migrations.AddField(
            model_name='problem',
            name='lastModifyUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prob_modifyUser', to='box.User'),
        ),
        migrations.AddField(
            model_name='problem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.Plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='createUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_createUser', to='box.User'),
        ),
        migrations.AddField(
            model_name='plan',
            name='lastModifyUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_modifyUser', to='box.User'),
        ),
        migrations.AddField(
            model_name='buginfo',
            name='bugSource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.BugSource'),
        ),
        migrations.AddField(
            model_name='buginfo',
            name='lineName',
            field=models.ManyToManyField(through='box.Bug2LineName', to='box.Line'),
        ),
        migrations.AddField(
            model_name='buginfo',
            name='notifyPeople',
            field=models.ManyToManyField(through='box.Bug2NotiPeople', to='box.NotiPeople'),
        ),
        migrations.AddField(
            model_name='buginfo',
            name='platformName',
            field=models.ManyToManyField(through='box.Bug2Platform', to='box.Platform'),
        ),
        migrations.AddField(
            model_name='buginfo',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.BugLevel'),
        ),
        migrations.AddField(
            model_name='buginfo',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.Problem'),
        ),
        migrations.AddField(
            model_name='buginfo',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.BugReason'),
        ),
        migrations.AddField(
            model_name='bug2platform',
            name='bugID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.BugInfo'),
        ),
        migrations.AddField(
            model_name='bug2platform',
            name='lineNameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.Platform'),
        ),
        migrations.AddField(
            model_name='bug2notipeople',
            name='bugID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.BugInfo'),
        ),
        migrations.AddField(
            model_name='bug2notipeople',
            name='notipeople',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.NotiPeople'),
        ),
        migrations.AddField(
            model_name='bug2linename',
            name='bugID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.BugInfo'),
        ),
        migrations.AddField(
            model_name='bug2linename',
            name='lineNameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.Line'),
        ),
    ]
